### PR TITLE
Fix halide baseline rules

### PR DESCRIPTION
**Pull request by ajpal**
lmao we just weren't parsing these right

### CODE REVIEW

**Review by chandrakananandi — APPROVED** [review]
LOL great catch 😂

**Comment by vee-effekt** [comment]
What does this mean exactly? Are the current results wrong?

**Comment by ajpal** [comment]
> What does this mean exactly? Are the current results wrong?

This won't change the results using enumo rules to derive the halide ones.
But without the `?` in the halide rules, the variables weren't being parsed as pattern variables (so for example the rule `(! (! x)) ==> x` would only match a variable enode literally named `x`). The halide->enumo derivability was saying 0 for everything (and I think we always knew this was suspect but just hadn't had a chance to dig into). This should fix that direction.
Screenshot 2023-04-08 at 10 13 24 PM

**Comment by vee-effekt** [comment]
ooooooooo okay great

**Pull request merged**
