### PR TITLE
Add interval analysis option for constant folding

### PR DESCRIPTION
**Pull request by ajpal**
I'm not sure the best way to test this, let me know if you have suggestions.
I manually checked by printing out each fold, and this finds the exact same folds as CvecMatching for iters 1 and 2 for rationals

### CODE REVIEW

**Comment by bksaiki** [comment]
That is tough. I'm assuming it's good if it doesn't affect our expect tests.

**Review by bksaiki — COMMENTED** [review]
Other than the extraneous `println!`, looks good to me!

**Review by bksaiki — APPROVED** [review]
Sorry! I meant to choose approve.

**Review by chandrakananandi — APPROVED** [review]
Very glad about this! :shipit:

**Pull request merged**
